server:
  port: 8085

spring:
  application:
    name: notification-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      notification-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

# Notification Configuration
notification:
  email:
    enabled: true
    templates-path: classpath:/templates/
  sms:
    enabled: false

logging:
  level:
    com.ekart: DEBUG
