server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ekart
    username: ekart
    password: ekart123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

keycloak:
  auth-server-url: http://localhost:8090
  realm: ekart
  resource: ekart-client
  credentials:
    secret: Dm7thf9XM9uG88u4cuH8EQA3ETTU5jYa
  use-resource-role-mappings: true
  bearer-only: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 1s

logging:
  level:
    com.ekart: DEBUG
    org.springframework.security: DEBUG
