server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/,file:./config/
        composite:
          - type: native
            search-locations: classpath:/config/,file:./config/
          - type: git
            uri: https://github.com/example/config-repo
            clone-on-start: false
            default-label: main
            timeout: 5
            skip-ssl-validation: true
  profiles:
    active: native,composite
  security:
    user:
      name: admin
      password: config123

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ekart: DEBUG
    org.springframework.cloud.config: DEBUG
