version: '3.8'

services:
  # Keycloak for Authentication
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
    ports:
      - "8090:8080"
    depends_on:
      - keycloak-db
    command: start-dev

  # Keycloak Database
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # PostgreSQL for User and Product Services
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=ekart
      - POSTGRES_USER=ekart
      - POSTGRES_PASSWORD=ekart123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # MongoDB for Order Service
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ekart
      - MONGO_INITDB_ROOT_PASSWORD=ekart123
      - MONGO_INITDB_DATABASE=orders
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  # MySQL for Payment Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=payments
      - MYSQL_USER=ekart
      - MYSQL_PASSWORD=ekart123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Redis for Notification Service
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Kafka for Event Streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  keycloak_data:
  postgres_data:
  mongodb_data:
  mysql_data:
  redis_data:

networks:
  default:
    name: ekart-network
